export var multi = 
[
    {"name":"Quezon City","series":[{"name":"deaths","value":53},{"name":"recovered","value":28}]},
{"name":"City of Manila","series":[{"name":"deaths","value":24},{"name":"recovered","value":10}]},
{"name":"City of Paranaque","series":[{"name":"deaths","value":12},{"name":"recovered","value":6}]},
{"name":"Rizal","series":[{"name":"deaths","value":19},{"name":"recovered","value":8}]},
{"name":"City of Pasig","series":[{"name":"deaths","value":20},{"name":"recovered","value":16}]},
{"name":"Laguna","series":[{"name":"deaths","value":6},{"name":"recovered","value":4}]},
{"name":"Cavite","series":[{"name":"deaths","value":17},{"name":"recovered","value":3}]},
{"name":"Caloocan City","series":[{"name":"deaths","value":11},{"name":"recovered","value":2}]},
{"name":"City of Muntinlupa","series":[{"name":"deaths","value":8},{"name":"recovered","value":0}]},
{"name":"City of Marikina","series":[{"name":"deaths","value":8},{"name":"recovered","value":5}]},
{"name":"Bulacan","series":[{"name":"deaths","value":15},{"name":"recovered","value":4}]},
{"name":"Batangas","series":[{"name":"deaths","value":13},{"name":"recovered","value":11}]},
{"name":"City of Valenzuela","series":[{"name":"deaths","value":2},{"name":"recovered","value":0}]},
{"name":"Pampanga","series":[{"name":"deaths","value":5},{"name":"recovered","value":0}]},
{"name":"Bataan","series":[{"name":"deaths","value":2},{"name":"recovered","value":1}]},
{"name":"Cebu","series":[{"name":"deaths","value":6},{"name":"recovered","value":0}]},
{"name":"Pangasinan","series":[{"name":"deaths","value":7},{"name":"recovered","value":0}]},
{"name":"Quezon","series":[{"name":"deaths","value":4},{"name":"recovered","value":3}]},
{"name":"Iloilo","series":[{"name":"deaths","value":5},{"name":"recovered","value":2}]},
{"name":"City of Navotas","series":[{"name":"deaths","value":2},{"name":"recovered","value":0}]},
{"name":"Zambales","series":[{"name":"deaths","value":2},{"name":"recovered","value":0}]},
{"name":"La Union","series":[{"name":"deaths","value":3},{"name":"recovered","value":0}]},
{"name":"Lanao del Sur","series":[{"name":"deaths","value":3},{"name":"recovered","value":0}]},
{"name":"Negros Oriental","series":[{"name":"deaths","value":3},{"name":"recovered","value":2}]},
{"name":"Lanao del Norte","series":[{"name":"deaths","value":2},{"name":"recovered","value":0}]},
{"name":"Occidental Mindoro","series":[{"name":"deaths","value":2},{"name":"recovered","value":0}]},
{"name":"Sultan Kudarat","series":[{"name":"deaths","value":1},{"name":"recovered","value":0}]},

]