export var multi =[
    {"name":"Quezon City","series":[{"name":"deaths","value":53},{"name":"recovered","value":28}]},
    {"name":"City of Manila","series":[{"name":"deaths","value":24},{"name":"recovered","value":10}]},
    {"name":"City of Makati","series":[{"name":"deaths","value":7},{"name":"recovered","value":21}]},
    {"name":"City of Paranaque","series":[{"name":"deaths","value":12},{"name":"recovered","value":6}]},
    {"name":"Rizal","series":[{"name":"deaths","value":19},{"name":"recovered","value":8}]},
    {"name":"City of Mandaluyong","series":[{"name":"deaths","value":6},{"name":"recovered","value":7}]},
    {"name":"City of Pasig","series":[{"name":"deaths","value":20},{"name":"recovered","value":16}]},
    {"name":"Laguna","series":[{"name":"deaths","value":6},{"name":"recovered","value":4}]},
    {"name":"Taguig City","series":[{"name":"deaths","value":5},{"name":"recovered","value":12}]},
    {"name":"Cavite","series":[{"name":"deaths","value":17},{"name":"recovered","value":3}]},
    {"name":"City of San Juan","series":[{"name":"deaths","value":11},{"name":"recovered","value":13}]},
    {"name":"Pasay City","series":[{"name":"deaths","value":3},{"name":"recovered","value":6}]},
    {"name":"Caloocan City","series":[{"name":"deaths","value":11},{"name":"recovered","value":2}]},
    {"name":"City of Muntinlupa","series":[{"name":"deaths","value":8},{"name":"recovered","value":0}]},
    {"name":"City of Las Pinas","series":[{"name":"deaths","value":3},{"name":"recovered","value":4}]},
    {"name":"City of Marikina","series":[{"name":"deaths","value":8},{"name":"recovered","value":5}]},
    {"name":"Bulacan","series":[{"name":"deaths","value":15},{"name":"recovered","value":4}]},
    {"name":"Davao del Sur","series":[{"name":"deaths","value":14},{"name":"recovered","value":35}]},
    {"name":"Batangas","series":[{"name":"deaths","value":13},{"name":"recovered","value":11}]},
    {"name":"City of Valenzuela","series":[{"name":"deaths","value":2},{"name":"recovered","value":0}]},
    {"name":"Pampanga","series":[{"name":"deaths","value":5},{"name":"recovered","value":0}]},
    {"name":"Nueva Ecija","series":[{"name":"deaths","value":0},{"name":"recovered","value":1}]},
    {"name":"Bataan","series":[{"name":"deaths","value":2},{"name":"recovered","value":1}]},
    {"name":"Cebu","series":[{"name":"deaths","value":6},{"name":"recovered","value":0}]},
    {"name":"Pangasinan","series":[{"name":"deaths","value":7},{"name":"recovered","value":0}]},
    {"name":"Quezon","series":[{"name":"deaths","value":4},{"name":"recovered","value":3}]},
    {"name":"Tarlac","series":[{"name":"deaths","value":1},{"name":"recovered","value":6}]},
    {"name":"City of Malabon","series":[{"name":"deaths","value":0},{"name":"recovered","value":0}]},
    {"name":"Iloilo","series":[{"name":"deaths","value":5},{"name":"recovered","value":2}]},
    {"name":"Benquet","series":[{"name":"deaths","value":1},{"name":"recovered","value":1}]},
    {"name":"Pateros","series":[{"name":"deaths","value":0},{"name":"recovered","value":1}]},
    {"name":"City of Navotas","series":[{"name":"deaths","value":2},{"name":"recovered","value":0}]},
    {"name":"Zambales","series":[{"name":"deaths","value":2},{"name":"recovered","value":0}]},
    {"name":"Cagayan","series":[{"name":"deaths","value":0},{"name":"recovered","value":7}]},
    {"name":"La Union","series":[{"name":"deaths","value":3},{"name":"recovered","value":0}]},
    {"name":"Albay","series":[{"name":"deaths","value":0},{"name":"recovered","value":0}]},
    {"name":"Davai del Norte","series":[{"name":"deaths","value":0},{"name":"recovered","value":0}]},
    {"name":"Negros Occidental","series":[{"name":"deaths","value":1},{"name":"recovered","value":2}]},
    {"name":"Zamboanga del Sur","series":[{"name":"deaths","value":0},{"name":"recovered","value":0}]},
    {"name":"Isabela","series":[{"name":"deaths","value":0},{"name":"recovered","value":1}]},
    {"name":"Camarines Sur","series":[{"name":"deaths","value":0},{"name":"recovered","value":1}]},
    {"name":"Aklan","series":[{"name":"deaths","value":0},{"name":"recovered","value":0}]},
    {"name":"Lanao del Sur","series":[{"name":"deaths","value":3},{"name":"recovered","value":0}]},
    {"name":"Negros Oriental","series":[{"name":"deaths","value":3},{"name":"recovered","value":2}]},
    {"name":"Cotabato City","series":[{"name":"deaths","value":0},{"name":"recovered","value":2}]},
    {"name":"Lanao del Norte","series":[{"name":"deaths","value":2},{"name":"recovered","value":0}]},
    {"name":"Oriental Mindoro","series":[{"name":"deaths","value":0},{"name":"recovered","value":1}]},
    {"name":"Nueva Vizcaya","series":[{"name":"deaths","value":1},{"name":"recovered","value":2}]},
    {"name":"Capiz","series":[{"name":"deaths","value":1},{"name":"recovered","value":1}]},
    {"name":"Marinduque","series":[{"name":"deaths","value":0},{"name":"recovered","value":1}]},
    {"name":"South Cotabato","series":[{"name":"deaths","value":0},{"name":"recovered","value":0}]},
    {"name":"Abra","series":[{"name":"deaths","value":0},{"name":"recovered","value":1}]},
    {"name":"Cotabato (North Cotabato)","series":[{"name":"deaths","value":0},{"name":"recovered","value":0}]},
    {"name":"Davao Oriental","series":[{"name":"deaths","value":0},{"name":"recovered","value":0}]},
    {"name":"Ilocos Norte","series":[{"name":"deaths","value":0},{"name":"recovered","value":0}]},
    {"name":"Occidental Mindoro","series":[{"name":"deaths","value":2},{"name":"recovered","value":0}]},
    {"name":"Samar","series":[{"name":"deaths","value":0},{"name":"recovered","value":0}]},
    {"name":"Sultan Kudarat","series":[{"name":"deaths","value":1},{"name":"recovered","value":0}]},
    {"name":"Compostela Valley","series":[{"name":"deaths","value":0},{"name":"recovered","value":1}]},
    {"name":"Misamis Occidental","series":[{"name":"deaths","value":0},{"name":"recovered","value":0}]},
    {"name":"Agusan del Norte","series":[{"name":"deaths","value":0},{"name":"recovered","value":0}]},
    {"name":"Antique","series":[{"name":"deaths","value":0},{"name":"recovered","value":0}]},
    {"name":"Bukidnon","series":[{"name":"deaths","value":0},{"name":"recovered","value":0}]},
    {"name":"Camiguin","series":[{"name":"deaths","value":0},{"name":"recovered","value":0}]},
    {"name":"Catanduanes","series":[{"name":"deaths","value":0},{"name":"recovered","value":0}]},
    {"name":"Ilocos Sur","series":[{"name":"deaths","value":0},{"name":"recovered","value":0}]},
    {"name":"Maguindanao","series":[{"name":"deaths","value":0},{"name":"recovered","value":0}]},
    {"name":"Romblon","series":[{"name":"deaths","value":0},{"name":"recovered","value":0}]},
    
]